Error on unresolved (undefined) symbols
Linking example/hello.c without libc, for instance, results in

toslink: error: example/HELLO.TOS.o: undefined reference to `printf'

Fixes: cfb16052ae35 ("Replace -L$libdir -lc command argument with prg.ld linker script")